---
- name: Openshift IPI
  user: ansible
  hosts: local
  connection: local 
  gather_facts: false
  module_defaults:
    get_url:
      timeout: 60
  vars_files:
  - ocp 
  roles:
  - role: openshift-ipi
